[pytest]
DJANGO_SETTINGS_MODULE = TicketAPI_Poncho.settings_testing

testpaths = apps

python_files = test_*.py tests.py

# --nomigrations: arma el esquema directo desde los modelos (mucho mas rapido,
# no corre el historial de migraciones).

# -ra:            muestra el resumen de tests que no pasaron al final.
addopts = --nomigrations -ra
