# Generated by Django 6.0.5 on 2026-05-28 00:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('artista_principal', models.CharField(max_length=150)),
                ('spotify_art_id', models.CharField(max_length=100)),
                ('bkp_spotify_popularity', models.IntegerField(default=0)),
                ('fecha', models.DateField(default=None)),
                ('lugar', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SectorEntrada',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_sector', models.CharField(max_length=100)),
                ('capacidad_maxima', models.IntegerField()),
                ('entradas_vendidas', models.IntegerField(default=0)),
                ('precio_base_ars', models.DecimalField(decimal_places=2, max_digits=12)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='core.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_final_ars', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bkp_precio_USD', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('sector_entrada', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.sectorentrada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
