# Generated by Django 6.0.5 on 2026-05-26 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('artista_principal', models.CharField(max_length=150)),
                ('spotify_art_id', models.CharField(max_length=100)),
                ('bkp_spotify_popularity', models.IntegerField(default=0)),
                ('fecha_hora', models.DateTimeField()),
                ('lugar', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SectorEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sector', models.CharField(max_length=100)),
                ('capacidad_maxima', models.IntegerField()),
                ('entradas_vendidas', models.IntegerField(default=0)),
                ('precio_base_ars', models.DecimalField(decimal_places=2, max_digits=12)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='core.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_final_ars', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bkp_precio_USD', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('sector_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sectorentrada')),
            ],
        ),
    ]
