# Generated by Django 5.2.14 on 2026-05-30 02:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evento",
            old_name="bkp_spotify_popularity",
            new_name="bkp_coeficiente_pop",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="spotify_art_id",
        ),
    ]
