# Generated by Django 5.2.14 on 2026-05-26 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sectorentrada",
            old_name="evento",
            new_name="evento_id",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="usuario",
            new_name="usuario_id",
        ),
        migrations.RemoveField(
            model_name="evento",
            name="fecha_hora",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="sector_entrada",
        ),
        migrations.AddField(
            model_name="evento",
            name="fecha",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="ticket",
            name="sector_entrada_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="core.sectorentrada",
            ),
        ),
    ]
