# Generated by Django 5.2.14 on 2026-05-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0002_rename_bkp_spotify_popularity_evento_bkp_coeficiente_pop_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="preventa",
            field=models.DateField(default=None),
        ),
    ]
