# Generated by Django 5.2.14 on 2026-05-30 02:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_evento_preventa"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evento",
            old_name="bkp_coeficiente_pop",
            new_name="coeficiente_pop",
        ),
    ]
