# Generated by Django 5.2.14 on 2026-05-27 00:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_evento_sectorentrada_evento_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sectorentrada",
            old_name="evento_id",
            new_name="evento",
        ),
    ]
