# Generated by Django 5.2.14 on 2026-05-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_bkp_coeficiente_pop_evento_coeficiente_pop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="coeficiente_pop",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
