# Generated by Django 5.2.14 on 2026-05-27 01:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_rename_evento_id_sectorentrada_evento"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="sector_entrada_id",
            new_name="sector_entrada",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="usuario_id",
            new_name="usuario",
        ),
    ]
