# Generated by Django 5.2.14 on 2026-05-31 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_evento_coeficiente_pop"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evento",
            name="coeficiente_pop",
        ),
        migrations.AddField(
            model_name="evento",
            name="bkp_reproducciones",
            field=models.IntegerField(default=0),
        ),
    ]
